
const data1 = [
     { course: "thejoyofcomputingusingpython", count: 1409, mean: 85.9891909155429, median: 90, mode: "91" },
 { course: "psychologyoflearning", count: 829, mean: 94.2825814234017, median: 97, mode: "99" },
 { course: "socialinnovationinindustry4.0", count: 547, mean: 88.1957404021938, median: 90, mode: "94" },
 { course: "wildlifeecology", count: 500, mean: 97.882, median: 100, mode: "100" },
 { course: "cloudcomputing", count: 281, mean: 82.7082206405694, median: 84, mode: "82" },
 { course: "physicsofrenewableenergysystems", count: 187, mean: 76.8207486631016, median: 79, mode: "70, 86, 90" },
 { course: "introductiontointernetofthings", count: 133, mean: 87.5139097744361, median: 90, mode: "90" },
 { course: "joyofcomputingusingpython", count: 109, mean: 84.5045871559633, median: 87, mode: "94" },
 { course: "softskills", count: 67, mean: 73.1868656716418, median: 77, mode: "77" },
 { course: "foundationsofrsoftware", count: 63, mean: 90.088253968254, median: 91, mode: "90" },
 { course: "programminginjava", count: 62, mean: 70.1777419354839, median: 72, mode: "75" },
 { course: "appliedlinearalgebraforsignalprocessing,dataanalyticsandmachinelearning", count: 61, mean: 88.5245901639344, median: 91, mode: "94" },
 { course: "gettingstartedwithcompetitiveprogramming", count: 54, mean: 75.3333333333333, median: 75.5, mode: "75" },
 { course: "conservationgeography", count: 47, mean: 96.063829787234, median: 99, mode: "100" },
 { course: "cybersecurityandprivacy", count: 44, mean: 69.9320454545455, median: 69.5, mode: "74" },
 { course: "environmentalscience", count: 40, mean: 65.0445, median: 65, mode: "55, 68, 73" },
 { course: "psychologyoflearning(noc24-hs117)", count: 39, mean: 93.2215384615385, median: 99, mode: "99" },
 { course: "educationforsustainabledevelopment", count: 34, mean: 97.1764705882353, median: 100, mode: "100" },
 { course: "ethicalhacking", count: 34, mean: 74.8441176470588, median: 79, mode: "86" },
 { course: "programminginmodernc++", count: 32, mean: 66.4375, median: 66, mode: "56, 66, 70" },
 { course: "economicsofbankingandfinancemarkets", count: 27, mean: 81.7537037037037, median: 81, mode: "80" },
 { course: "forestsandtheirmanagement", count: 26, mean: 94.1538461538462, median: 98, mode: "98" },
 { course: "socialnetworks", count: 26, mean: 69.3076923076923, median: 70, mode: "70" },
 { course: "operatingsystemfundamentals", count: 24, mean: 72.7083333333333, median: 73, mode: "75" },
 { course: "introductiontoindustry4.0andindustrialinternetofthings", count: 23, mean: 75.8695652173913, median: 78, mode: "78" },
 { course: "joyofcomputingwithpython", count: 21, mean: 78.4761904761905, median: 77, mode: "88" },
 { course: "physicsoffunctionalmaterials&devices", count: 21, mean: 76, median: 73, mode: "72" },
 { course: "thejoyofcomputingwithpython", count: 19, mean: 83.8947368421053, median: 85, mode: "79, 85, 91" },
 { course: "e-business", count: 18, mean: 68.1666666666667, median: 67.5, mode: "77" },
 { course: "businesstobusinessmarketing(b2b)", count: 15, mean: 68.8666666666667, median: 72, mode: "75" },
 { course: "ecologyandsociety", count: 15, mean: 68.6, median: 63, mode: "94" },
 { course: "thejoyofcomputingpython", count: 14, mean: 85.5714285714286, median: 86, mode: "80, 82, 85, 86, 87, 88, 91" },
 { course: "physicsofrenewableenergysystem", count: 14, mean: 76.2714285714286, median: 77, mode: "77" },
 { course: "publicspeaking", count: 14, mean: 66, median: 66, mode: "66, 72" },
 { course: "organizationalbehaviour", count: 12, mean: 82.5, median: 86, mode: "88" },
 { course: "educationalleadership", count: 11, mean: 96.9090909090909, median: 98, mode: "98, 99" },
 { course: "conservationeconomics", count: 11, mean: 94.4545454545455, median: 97, mode: "100" },
 { course: "productandbrandmanagement", count: 11, mean: 72.7272727272727, median: 75, mode: "67, 72, 75, 77, 79" },
 { course: "joyofcomputinginpython", count: 11, mean: 77.8181818181818, median: 70, mode: "70" },
 { course: "forestandtheirmanagement", count: 10, mean: 94.9, median: 98, mode: "98" },
 { course: "projectmanagementformanagers", count: 10, mean: 79.376, median: 81.38, mode: "73, 81.38, 86" },
 { course: "electronicsystemsforcancerdiagnosis", count: 10, mean: 80, median: 79, mode: "78" },
 { course: "joyofcomputing", count: 10, mean: 74.6, median: 77, mode: "64, 67, 77, 79, 86" },
 { course: "joyofcomputingpython", count: 10, mean: 75, median: 75, mode: "58, 63, 75, 88, 91" },
//  { course: "100", count: 9, mean: 75.5555555555556, median: 73, mode: "64, 73, 90" },
 { course: "datastructureandalgorithmsusingjava", count: 9, mean: 72.3333333333333, median: 71, mode: "71" },
 { course: "physicsofrenewablesystem", count: 9, mean: 68.4444444444444, median: 69, mode: "75" },
 { course: "businesstobusinessmarketing", count: 9, mean: 67.6666666666667, median: 65, mode: "60, 64, 68, 80" },
 { course: "entrepreneurship", count: 8, mean: 88.1725, median: 88, mode: "85.69, 86, 90, 91" },
 { course: "introductiontomachinelearning", count: 8, mean: 71.625, median: 78, mode: "78" },
 { course: "scientificcomputingusingpython", count: 8, mean: 76.375, median: 75, mode: "70, 75, 90" },
 { course: "sustainabletransportationsystems", count: 8, mean: 70.5, median: 71, mode: "71" },
 { course: "pyschologyoflearning", count: 7, mean: 96.1428571428571, median: 97, mode: "92, 97, 98" },
 { course: "theoryofproductionprocesses", count: 7, mean: 77.5714285714286, median: 81, mode: "64, 81, 83" },
 { course: "smartgrid:basicstoadvancedtechnologies", count: 7, mean: 74.7142857142857, median: 79, mode: "79, 80" },
 { course: "wastewatertreatmentandrecycling", count: 7, mean: 76.1171428571429, median: 75, mode: "60.41, 95" },
 { course: "introductiontofuzzysettheory,arithmeticandlogic", count: 7, mean: 62.4285714285714, median: 61, mode: "61" },
 { course: "foundationofrsoftware", count: 6, mean: 89, median: 91, mode: "81, 91, 95" },
 { course: "mathematicsforeconomics-i", count: 6, mean: 87.3333333333333, median: 88, mode: "84, 88, 90" },
 { course: "physicsoffunctionalmaterialsanddevices", count: 6, mean: 82.3333333333333, median: 80, mode: "77, 80, 90" },
 { course: "electronicsystemsdesign:hands-oncircuitsandpcbdesignwithcadsoftware", count: 6, mean: 76.3333333333333, median: 77, mode: "77" },
 { course: "industrialsafetyengineering", count: 6, mean: 75, median: 73, mode: "72, 73, 80" },
 { course: "design&implementationofhuman-computerinterfaces", count: 6, mean: 68.3333333333333, median: 67, mode: "66, 67, 72" },
 { course: "socialnetworkanalysis", count: 6, mean: 54, median: 47, mode: "37, 47, 78" },
 { course: "fuzzysets,logicandsystems&applications", count: 5, mean: 88, median: 96, mode: "99" },
 { course: "thejoycomputingusingpython", count: 5, mean: 92.8, median: 94, mode: "94" },
 { course: "municipalsolidwastemanagement", count: 5, mean: 78.8, median: 82, mode: "71, 85" },
 { course: "simulationofcommunicationsystemsusingmatlab", count: 5, mean: 76.4, median: 81, mode: "81, 83" },
 { course: "fundamentalsofartificialintelligence", count: 5, mean: 72, median: 73, mode: "73" },
 { course: "softwaretesting", count: 5, mean: 74, median: 73, mode: "68, 73" },
 { course: "practicalcybersecurityforcybersecuritypractitioners", count: 4, mean: 96.5, median: 96.5, mode: "96, 97" },
 { course: "psycologyoflearning", count: 4, mean: 96.5, median: 96.5, mode: "94, 99" },
 { course: "foundationinrsoftware", count: 4, mean: 93, median: 93, mode: "88, 98" },
 { course: "thejoyofcomputingusingpyhton", count: 4, mean: 92.5, median: 92.5, mode: "88, 97" },
 { course: "conservationalgeography", count: 4, mean: 92, median: 92, mode: "85, 99" },
 { course: "socialinnovation4.0", count: 4, mean: 88.5, median: 88.5, mode: "87, 90" },
 { course: "environmentalstudies", count: 4, mean: 87, median: 87, mode: "82, 92" },
 { course: "hranalytics", count: 4, mean: 86, median: 86, mode: "77, 95" },
 { course: "socialinnovationinindustry2.0", count: 4, mean: 83.5, median: 83.5, mode: "76, 91" },
 { course: "carbonaccountingandsustainabledesignsinproductlifecyclemanagement", count: 4, mean: 81.5, median: 81.5, mode: "78, 85" },
 { course: "thejoyofcomputing", count: 4, mean: 78.25, median: 80, mode: "80" },
 { course: "introductiontowesternpoliticalthought", count: 4, mean: 78, median: 78, mode: "73, 83" },
 { course: "classicalsociologicaltheory", count: 4, mean: 76, median: 76, mode: "75, 77" },
 { course: "nanophotonics,plasmonicsandmetamaterials", count: 4, mean: 75.5, median: 75.5, mode: "75, 76" },
 { course: "physicsofrenewablesystems", count: 4, mean: 73, median: 73, mode: "60, 86" },
 { course: "worksystemdesign", count: 4, mean: 68.5, median: 68.5, mode: "67, 70" },
 { course: "softskill", count: 4, mean: 68.22, median: 68.22, mode: "61.44, 75" },
 { course: "industrialrobotics:theoriesforimplementation", count: 4, mean: 68, median: 68, mode: "68" },
 { course: "designofphotovoltaicsystems", count: 4, mean: 67.5, median: 67.5, mode: "63, 72" },
 { course: "internetofthings", count: 4, mean: 67.5, median: 67.5, mode: "58, 77" },
 { course: "programinginjava", count: 4, mean: 64.5, median: 64.5, mode: "61, 68" },
 { course: "bridgeengineering", count: 4, mean: 50.5, median: 50.5, mode: "50, 51" },
 { course: "statisticsforbiomedicalengineers", count: 3, mean: 86.6666666666667, median: 92, mode: "92" },
 { course: "responsible&safeaisystems", count: 3, mean: 74.3333333333333, median: 81, mode: "81" },
 { course: "strategicmanagement", count: 3, mean: 72, median: 80, mode: "80" },
 { course: "airpollutionandcontrol", count: 3, mean: 76.3333333333333, median: 77, mode: "No unique mode" },
 { course: "ebusiness", count: 3, mean: 72.3333333333333, median: 77, mode: "77" },
 { course: "appliedergonomics", count: 3, mean: 73, median: 75, mode: "No unique mode" },
 { course: "introductiontocognitivepsychology", count: 3, mean: 68.3333333333333, median: 75, mode: "75" },
 { course: "vlsidesignflow:rtltogds", count: 3, mean: 73.6666666666667, median: 73, mode: "73" },
 { course: "availabilityandmanagementofgroundwaterresources", count: 3, mean: 66, median: 65, mode: "No unique mode" },
 { course: "introductiontodatabasesystems", count: 3, mean: 62, median: 61, mode: "61" },
 { course: "railwayengineering", count: 3, mean: 53, median: 53, mode: "53" },
 { course: "wilflifeecology", count: 2, mean: 100, median: 100, mode: "100" },
 { course: "thepsycologyoflearning", count: 2, mean: 98, median: 98, mode: "98" },
 { course: "joyofcomputingusingpyhton", count: 2, mean: 97, median: 97, mode: "97" },
 { course: "martgrid:basicstoadvancedtechnologies", count: 2, mean: 97, median: 97, mode: "97" },
 { course: "pschologyoflearning", count: 2, mean: 97, median: 97, mode: "97" },
 { course: "psychologyoflearing", count: 2, mean: 97, median: 97, mode: "97" },
 { course: "wildlifeandecology", count: 2, mean: 96, median: 96, mode: "96" },
 { course: "mathematicsforeconomics-1", count: 2, mean: 95, median: 95, mode: "95" },
 { course: "physcologyoflearning", count: 2, mean: 95, median: 95, mode: "95" },
 { course: "socialinnovationinindustrial4.0", count: 2, mean: 95, median: 95, mode: "95" },
 { course: "wastewatertreatmentandrecycling(ce105)", count: 2, mean: 95, median: 95, mode: "95" },
 { course: "aircraftpropulsion", count: 2, mean: 94, median: 94, mode: "94" },
 { course: "economicsofbankingandfinancialmarkets", count: 2, mean: 94, median: 94, mode: "94" },
 { course: "appliedlinearalgebraforsignalprocessing,dataanalyticsandmachinelearning,iitkanpur", count: 2, mean: 93, median: 93, mode: "93" },
 { course: "engineeringmetrology", count: 2, mean: 93, median: 93, mode: "93" },
 { course: "computationalcomplexity", count: 2, mean: 90, median: 90, mode: "90" },
 { course: "socialinnovationandindustry4.0", count: 2, mean: 90, median: 90, mode: "90" },
 { course: "metaladditivemanufacturing", count: 2, mean: 89.5, median: 89.5, mode: "No unique mode" },
 { course: "joyofcomputingusingpyton", count: 2, mean: 88, median: 88, mode: "88" },
 { course: "thejoyofprogrammingusingpython", count: 2, mean: 88, median: 88, mode: "88" },
 { course: "edcationalleadership", count: 2, mean: 86, median: 86, mode: "86" },
 { course: "mathematicsforeconomics", count: 2, mean: 86, median: 86, mode: "86" },
 { course: "datastructureandalgorithmwithjava", count: 2, mean: 84, median: 84, mode: "84" },
 { course: "socialinnovationinindustry4.o", count: 2, mean: 84, median: 84, mode: "84" },
 { course: "thejoyoncomputingusingpython", count: 2, mean: 83, median: 83, mode: "83" },
 { course: "5gwirelessstandarddesign", count: 2, mean: 82, median: 82, mode: "82" },
 { course: "deeplearning-iitropar", count: 2, mean: 82, median: 82, mode: "82" },
 { course: "microelectronics:devicestocircuits", count: 2, mean: 82, median: 82, mode: "82" },
 { course: "regressionanalysis", count: 2, mean: 82, median: 82, mode: "82" },
 { course: "sensorsandactuators", count: 2, mean: 81.5, median: 81.5, mode: "No unique mode" },
 { course: "artificialintelligence:searchmethodsforproblemsolving", count: 2, mean: 81, median: 81, mode: "81" },
 { course: "operationsmanagement", count: 2, mean: 81, median: 81, mode: "No unique mode" },
 { course: "phychologyoflearning", count: 2, mean: 78, median: 78, mode: "78" },
 { course: "introductiontoalgorithmsandanalysis", count: 2, mean: 77, median: 77, mode: "77" },
 { course: "physicsofrenewableenergysystems-online", count: 2, mean: 77, median: 77, mode: "77" },
 { course: "psychologyoflearningf", count: 2, mean: 77, median: 77, mode: "77" },
 { course: "softwartesting", count: 2, mean: 77, median: 77, mode: "77" },
 { course: "projectmanagementformanager", count: 2, mean: 76, median: 76, mode: "76" },
 { course: "thejoyofcomputinginpython", count: 2, mean: 76, median: 76, mode: "76" },
 { course: "dataanalyticswithpython", count: 2, mean: 75.5, median: 75.5, mode: "No unique mode" },
 { course: "algorithmicgametheory", count: 2, mean: 75, median: 75, mode: "75" },
 { course: "appliedlinearalgebraforsignalprocessing,dataanalytics,machinelearning", count: 2, mean: 75, median: 75, mode: "75" },
 { course: "buildingmaterialsasacornerstonetosustainability", count: 2, mean: 75, median: 75, mode: "75" },
 { course: "buisnesstobuisnessmarketing(b2b)", count: 2, mean: 75, median: 75, mode: "75" },
 { course: "datascienceforengineers", count: 2, mean: 75, median: 75, mode: "75" },
 { course: "distributedoptimizationandmachinelearning", count: 2, mean: 75, median: 75, mode: "75" },
 { course: "electronicsystemsdesign_hands-oncircuitsandpcbdesignwithcadsoftware", count: 2, mean: 75, median: 75, mode: "75" },
 { course: "industrialtoindustry4.oandindustrialinternetofthing", count: 2, mean: 75, median: 75, mode: "75" },
 { course: "marketingmanagement-i", count: 2, mean: 75, median: 75, mode: "75" },
 { course: "operatingsystems", count: 2, mean: 75, median: 75, mode: "75" },
 { course: "urbanlanduseandtransportationplanning", count: 2, mean: 75, median: 75, mode: "75" },
 { course: "microwaveengineering", count: 2, mean: 72, median: 72, mode: "72" },
 { course: "physicsofrenewableenergysystemsnoc24-ph29", count: 2, mean: 72, median: 72, mode: "72" },
 { course: "machinelearninganddeeplearning-fundamentalsandapplications", count: 2, mean: 71.5, median: 71.5, mode: "No unique mode" },
 { course: "mooccourse301,mooccourse303", count: 2, mean: 71, median: 71, mode: "71" },
 { course: "googlecloudcomputingfoundations", count: 2, mean: 70, median: 70, mode: "No unique mode" },
 { course: "gettingstartedwithcompetitveprogramming", count: 2, mean: 69, median: 69, mode: "69" },
 { course: "businessintelligenceandanalytics", count: 2, mean: 68, median: 68, mode: "No unique mode" },
 { course: "introductiontoiot", count: 2, mean: 68, median: 68, mode: "68" },
 { course: "joyofcomputing:python", count: 2, mean: 68, median: 68, mode: "68" },
 { course: "machinelearningforsoilandcropmanagement", count: 2, mean: 67, median: 67, mode: "67" },
 { course: "science,technologyandsociety", count: 2, mean: 67, median: 67, mode: "67" },
 { course: "modernconstructionmaterials", count: 2, mean: 66.5, median: 66.5, mode: "No unique mode" },
 { course: "physicsofrenewableenergyresources", count: 2, mean: 65, median: 65, mode: "65" },
 { course: "enhancingsoftskillsandpersonality", count: 2, mean: 64.5, median: 64.5, mode: "No unique mode" },
 { course: "projectmanagement", count: 2, mean: 63.5, median: 63.5, mode: "No unique mode" },
 { course: "deeplearningforcomputervision", count: 2, mean: 61, median: 61, mode: "61" },
 { course: "introductiontoenvironmentaleconomics", count: 2, mean: 61, median: 61, mode: "No unique mode" },
 { course: "humanresourcedevelopment", count: 2, mean: 60, median: 60, mode: "60" },
 { course: "machinelearninganddeeplearning-fundamentalsandapplication", count: 2, mean: 60, median: 60, mode: "No unique mode" },
 { course: "constitutionofindiaandenvironmentalgovernance:administrativeandadjudicatoryprocess", count: 2, mean: 57, median: 57, mode: "57" },
 { course: "thejoyofcomputingusingpytho", count: 2, mean: 55, median: 55, mode: "55" },
 { course: "businesstobusiness", count: 2, mean: 52, median: 52, mode: "52" },
 { course: "projectmanegmentformanegers", count: 2, mean: 51, median: 51, mode: "51" },
 { course: "introductiontoself-drivingcars", count: 2, mean: 50.29965, median: 50.29965, mode: "No unique mode" },
 { course: "sustainablepowergenerationsystems", count: 2, mean: 50, median: 50, mode: "No unique mode" },
 { course: "analysisanddesignprincipleofmicrowaveantennas", count: 2, mean: 26, median: 26, mode: "No unique mode" },
 { course: "electricalmeasurementandelectronicinstruments", count: 2, mean: 22, median: 22, mode: "22" },
 { course: "bt20-forestandtheirmanagement", count: 1, mean: 100, median: 100, mode: "No unique mode" },
 { course: "bt20forestsandtheirmanagement", count: 1, mean: 100, median: 100, mode: "No unique mode" },
 { course: "chemicalhazards;toxicityandreactivity", count: 1, mean: 100, median: 100, mode: "No unique mode" },
 { course: "datamodellinginpowerbi", count: 1, mean: 100, median: 100, mode: "No unique mode" },
 { course: "datascientistcareertrack", count: 1, mean: 100, median: 100, mode: "No unique mode" },
 { course: "educationforsustinabledevelopment", count: 1, mean: 100, median: 100, mode: "No unique mode" },
 { course: "healthimpactsofchemicalsinconsumerproducts", count: 1, mean: 100, median: 100, mode: "No unique mode" },
 { course: "introductiontoenvironmentalengineeringandscience-fundamentalandsustainabilityconcepts", count: 1, mean: 100, median: 100, mode: "No unique mode" },
 { course: "learnethicalhackingfromscratch2024", count: 1, mean: 100, median: 100, mode: "No unique mode" },
 { course: "wildelifeecology", count: 1, mean: 100, median: 100, mode: "No unique mode" },
 { course: "wildlifeecologynoc24-bt59", count: 1, mean: 100, median: 100, mode: "No unique mode" },
//  { course: "97", count: 1, mean: 97, median: 97, mode: "No unique mode" },
 { course: "nanotechnology:amaker'scourse", count: 1, mean: 96.22, median: 96.22, mode: "No unique mode" },
 { course: "deeplearningwithtensorflow2", count: 1, mean: 96, median: 96, mode: "No unique mode" },
 { course: "cloudcomputng", count: 1, mean: 95, median: 95, mode: "No unique mode" },
 { course: "literature,cultureandmedia", count: 1, mean: 94, median: 94, mode: "No unique mode" },
 { course: "fundamentalsofobjectorientedprogramming", count: 1, mean: 93, median: 93, mode: "No unique mode" },
 { course: "joyofcomputationusingpython", count: 1, mean: 92, median: 92, mode: "No unique mode" },
 { course: "cloudcomputingmooccourse(mooc7)", count: 1, mean: 90, median: 90, mode: "No unique mode" },
 { course: "energyresources,economics,andsustainabilit", count: 1, mean: 90, median: 90, mode: "No unique mode" },
 { course: "groundimprovement", count: 1, mean: 90, median: 90, mode: "No unique mode" },
 { course: "socialinnovationinindustry", count: 1, mean: 90, median: 90, mode: "No unique mode" },
 { course: "energyresources,economics,andsustainablility", count: 1, mean: 86, median: 86, mode: "No unique mode" },
 { course: "logistics&supplychainmanagement", count: 1, mean: 86, median: 86, mode: "No unique mode" },
 { course: "buisnessintelligenceandanalytics", count: 1, mean: 84, median: 84, mode: "No unique mode" },
 { course: "principleofeconomics", count: 1, mean: 84, median: 84, mode: "No unique mode" },
 { course: "princpleofeconomics", count: 1, mean: 84, median: 84, mode: "No unique mode" },
 { course: "rapidmanufacturing", count: 1, mean: 82, median: 82, mode: "No unique mode" },
 { course: "introductiontosoftskills", count: 1, mean: 80.5, median: 80.5, mode: "No unique mode" },
 { course: "patternrecognitionandapplication", count: 1, mean: 80, median: 80, mode: "No unique mode" },
 { course: "cs113thejoyofcomputingusingpython", count: 1, mean: 79, median: 79, mode: "No unique mode" },
 { course: "educationofsustainabledevelopment", count: 1, mean: 79, median: 79, mode: "No unique mode" },
 { course: "businesstobusinessmarketingb2b", count: 1, mean: 78, median: 78, mode: "No unique mode" },
 { course: "deeplearningiitropar-online", count: 1, mean: 78, median: 78, mode: "No unique mode" },
 { course: "blockchainanditsapplications", count: 1, mean: 77, median: 77, mode: "No unique mode" },
 { course: "advancedmachiningprocesses", count: 1, mean: 76, median: 76, mode: "No unique mode" },
 { course: "fundamentalsofartificalintelligence", count: 1, mean: 75, median: 75, mode: "No unique mode" },
 { course: "moocagainstresearchmethodology", count: 1, mean: 75, median: 75, mode: "No unique mode" },
 { course: "animalphysiology", count: 1, mean: 73, median: 73, mode: "No unique mode" },
 { course: "e-bussiness", count: 1, mean: 73, median: 73, mode: "No unique mode" },
//  { course: "4", count: 1, mean: 72, median: 72, mode: "No unique mode" },
 { course: "networksecurity", count: 1, mean: 71, median: 71, mode: "No unique mode" },
 { course: "financialmathematics", count: 1, mean: 70, median: 70, mode: "No unique mode" },
 { course: "sustainabletransporationsystem", count: 1, mean: 70, median: 70, mode: "No unique mode" },
 { course: "vlsidesignflow-rtltogds", count: 1, mean: 69, median: 69, mode: "No unique mode" },
 { course: "developingsoftskillsandpersonality", count: 1, mean: 68, median: 68, mode: "No unique mode" },
 { course: "engineeringmechanics", count: 1, mean: 68, median: 68, mode: "No unique mode" },
 { course: "mooccourse", count: 1, mean: 68, median: 68, mode: "No unique mode" },
 { course: "mooccourses", count: 1, mean: 68, median: 68, mode: "No unique mode" },
 { course: "naturalhazards", count: 1, mean: 68, median: 68, mode: "No unique mode" },
 { course: "polymerprocessengineering", count: 1, mean: 68, median: 68, mode: "No unique mode" },
 { course: "computergraphics", count: 1, mean: 64, median: 64, mode: "No unique mode" },
 { course: "intellectualproperty", count: 1, mean: 64, median: 64, mode: "No unique mode" },
 { course: "earthsciencesforcivilengineering", count: 1, mean: 63, median: 63, mode: "No unique mode" },
 { course: "cloudcomuting", count: 1, mean: 62, median: 62, mode: "No unique mode" },
 { course: "wastetoenergyconversion", count: 1, mean: 62, median: 62, mode: "No unique mode" },
 { course: "introductiontomicroeconomicswithoutcalculus", count: 1, mean: 61, median: 61, mode: "No unique mode" },
 { course: "reinforcementlearning", count: 1, mean: 61, median: 61, mode: "No unique mode" },
 { course: "innovationinmarketingandmarketingofinnovation", count: 1, mean: 58, median: 58, mode: "No unique mode" },
 { course: "machinelearninganddeeplearningfundamentals", count: 1, mean: 58, median: 58, mode: "No unique mode" },
 { course: "computervisionandimageprocessing", count: 1, mean: 56, median: 56, mode: "No unique mode" },
 { course: "cs114deeplearningiitropar", count: 1, mean: 56, median: 56, mode: "No unique mode" },
 { course: "structuralgeology", count: 1, mean: 56, median: 56, mode: "No unique mode" },
 { course: "inddorairpollution:sources,effects,monitoring,controlandmodeling", count: 1, mean: 55, median: 55, mode: "No unique mode" },
 { course: "ruralwaterresourcesmanagement", count: 1, mean: 55, median: 55, mode: "No unique mode" },
 { course: "cybeesecurityandprivacy", count: 1, mean: 54, median: 54, mode: "No unique mode" },
 { course: "mooc301", count: 1, mean: 54, median: 54, mode: "No unique mode" },
 { course: "mooc303", count: 1, mean: 54, median: 54, mode: "No unique mode" },
 { course: "matrixcomputationanditsapplications", count: 1, mean: 53.75, median: 53.75, mode: "No unique mode" },
 { course: "designofmechanicaltransmissionsystem", count: 1, mean: 53, median: 53, mode: "No unique mode" },
 { course: "designofphotovoltaicsystem", count: 1, mean: 51, median: 51, mode: "No unique mode" },
 { course: "appliednumericalmethods", count: 1, mean: 48, median: 48, mode: "No unique mode" },
 { course: "quantitativeinvestmentmanagement", count: 1, mean: 47, median: 47, mode: "No unique mode" },
 { course: "consumerpsychology", count: 1, mean: 45, median: 45, mode: "No unique mode" },
 { course: "sportsperformanceandnutrition", count: 1, mean: 45, median: 45, mode: "No unique mode" },
 { course: "envirnmentalscience", count: 1, mean: 44, median: 44, mode: "No unique mode" },
 { course: "operationsandsupplychainmanagement", count: 1, mean: 44, median: 44, mode: "No unique mode" },
 { course: "systemadministrationanditinfrastructureservices", count: 1, mean: 0.9714, median: 0.9714, mode: "No unique mode" },
 { course: "organizationalbehavior-ii", count: 1, mean: 0.85, median: 0.85, mode: "No unique mode" },

    // ... ADD THE REST OF THE DATA FROM YOUR FIRST IMAGE HERE ...
];

const data2 = [
     { course: "educationforsustainabledevelopment", count: 571, mean: 99.0765323992995, median: 99, mode: "100" },
 { course: "introductiontointernetofthings", count: 477, mean: 90.6033123689727, median: 92, mode: "94" },
 { course: "forestsandtheirmanagement", count: 394, mean: 99.511421319797, median: 99, mode: "100" },
 { course: "cloudcomputing", count: 189, mean: 77.1180423280423, median: 78, mode: "75" },
 { course: "thejoyofcomputingusingpython", count: 169, mean: 77.8891124260355, median: 79, mode: "75" },
 { course: "conservationeconomics", count: 151, mean: 92.5277483443708, median: 96.69, mode: "100" },
 { course: "fuzzysets,logicandsystems&applications", count: 99, mean: 86.2682828282828, median: 90, mode: "97" },
 { course: "forestandtheirmanagement", count: 71, mean: 91.9577464788732, median: 97, mode: "100" },
 { course: "programminginjava", count: 38, mean: 79.5723684210526, median: 81.5, mode: "75" },
 { course: "dataanalyticswithpython", count: 33, mean: 75.2727272727273, median: 76, mode: "86" },
 { course: "understandingincubationandentrepreneurship", count: 32, mean: 95.71875, median: 96, mode: "95" },
 { course: "internetofthings", count: 32, mean: 86.668125, median: 91, mode: "97" },
 { course: "introductiontocognitivepsychology", count: 31, mean: 85.6129032258064, median: 86, mode: "84" },
 { course: "introductiontodatabasesystems", count: 28, mean: 64.9285714285714, median: 64.5, mode: "61" },
 { course: "operationsmanagement", count: 24, mean: 80.2916666666667, median: 80.5, mode: "83, 77, 85" },
 { course: "plasmaphysicsandapplications", count: 19, mean: 59.2105263157895, median: 61, mode: "42, 66, 46, 82" },
 { course: "psychologyofstress,healthandwell-being", count: 18, mean: 80.0555555555556, median: 79, mode: "90, 99" },
 { course: "privacyandsecurityinonlinesocialmedia", count: 16, mean: 77.5, median: 80, mode: "80, 82" },
 { course: "joyofcomputingusingpython", count: 15, mean: 77.7506666666667, median: 82, mode: "72" },
 { course: "airpollutionandcontrol", count: 15, mean: 77.208, median: 78, mode: "92.06, 85, 78, 58, 70" },
 { course: "thermalphysics", count: 15, mean: 61.8, median: 60, mode: "56" },
 { course: "computernetworksandinternetprotocol", count: 11, mean: 60.9090909090909, median: 60, mode: "68, 50, 60, 55" },
 { course: "strategiesforsustainabledesign", count: 10, mean: 82.155, median: 81.775, mode: "90, 85, 80" },
 { course: "sensorsandactuators", count: 10, mean: 77, median: 79, mode: "79, 75" },
 { course: "networksecurity", count: 9, mean: 72.2222222222222, median: 71, mode: "65, 63" },
 { course: "maternalinfantyoungchildnutrition", count: 8, mean: 82.375, median: 82.5, mode: "84" },
 { course: "environmentalgeosciences", count: 8, mean: 72.625, median: 69.5, mode: "64, 68" },
 { course: "financialmathematics", count: 8, mean: 65.625, median: 66, mode: "70" },
 { course: "fuzzysets,logicandsystemsandapplications", count: 7, mean: 73.7142857142857, median: 78, mode: "82" },
 { course: "vlsiphysicaldesignwithtiminganalysis", count: 7, mean: 73.4285714285714, median: 68, mode: "86" },
 { course: "forestsandtheirmanagement(noc25-bt20)", count: 6, mean: 99.6666666666667, median: 100, mode: "100" },
 { course: "introductiontoenvironmentaleconomics", count: 6, mean: 70.3333333333333, median: 71, mode: "No unique mode" },
 { course: "naturallanguageprocessing", count: 6, mean: 66.055, median: 67, mode: "No unique mode" },
 { course: "socialnetworks", count: 6, mean: 66.8333333333333, median: 63.5, mode: "60" },
 { course: "fundamentalsofobjectorientedprogramming", count: 5, mean: 85.2, median: 87, mode: "No unique mode" },
 { course: "biomedicalsignalprocessing", count: 5, mean: 58.204, median: 60.02, mode: "47" },
 { course: "forestsandtheirmanagment", count: 4, mean: 98, median: 98, mode: "No unique mode" },
 { course: "introductionofinternetofthings", count: 4, mean: 91.75, median: 91, mode: "91" },
 { course: "introductiontoindustry4.0andindustrialinternetofthings", count: 4, mean: 87.25, median: 85.5, mode: "No unique mode" },
 { course: "affectivecomputing", count: 4, mean: 80.5, median: 80.5, mode: "83, 78" },
 { course: "businessintelligence&analytics", count: 4, mean: 78, median: 76, mode: "No unique mode" },
 { course: "innovationinmarketingandmarketingofinnovation", count: 4, mean: 76, median: 76, mode: "84, 68" },
 { course: "discretemathematics", count: 4, mean: 73.75, median: 75, mode: "82" },
 { course: "introductiontolargelanguagemodels(llms)", count: 4, mean: 69.25, median: 71, mode: "71" },
 { course: "modernconstructionmaterials", count: 4, mean: 68, median: 69, mode: "No unique mode" },
 { course: "bt20forestsandtheirmanagement", count: 3, mean: 99, median: 100, mode: "100" },
 { course: "educationforsustainabledevelopment(noc25-hs12)", count: 3, mean: 99.6666666666667, median: 100, mode: "100" },
 { course: "educationforsustinabledevelopment", count: 3, mean: 98.6666666666667, median: 98, mode: "98" },
 { course: "conservationofeconomics", count: 3, mean: 96.3333333333333, median: 97, mode: "No unique mode" },
 { course: "fuzzysets,logicandsystemandapplication", count: 3, mean: 86.6666666666667, median: 97, mode: "97" },
 { course: "humancomputerinteraction(inenglish)", count: 3, mean: 93.6666666666667, median: 94, mode: "No unique mode" },
 { course: "internetofthings(iot)", count: 3, mean: 87.6666666666667, median: 87, mode: "No unique mode" },
 { course: "thejoyofcomputationusingpython", count: 3, mean: 85.3333333333333, median: 82, mode: "82" },
 { course: "blockchainanditsapplications", count: 3, mean: 71.3333333333333, median: 72, mode: "No unique mode" },
 { course: "thejoyofcomputingwithpython", count: 3, mean: 70.6666666666667, median: 70, mode: "No unique mode" },
 { course: "productdesignandmanufacturing", count: 3, mean: 71, median: 65, mode: "No unique mode" },
 { course: "businessintelligenceandanalytics", count: 3, mean: 45.3333333333333, median: 63, mode: "No unique mode" },
 { course: "compilerdesign", count: 3, mean: 57.3333333333333, median: 47, mode: "47" },
 { course: "forestandtheirmangement", count: 2, mean: 100, median: 100, mode: "100" },
 { course: "educationofsustainabledevelopment", count: 2, mean: 99.5, median: 99.5, mode: "No unique mode" },
 { course: "educationforsustainabledevelopment-online", count: 2, mean: 97, median: 97, mode: "97" },
 { course: "educationforsustainabledeveploment", count: 2, mean: 96, median: 96, mode: "96" },
 { course: "businessfundamentalsforentrepreneurs", count: 2, mean: 95, median: 95, mode: "95" },
 { course: "understandingincubation&entrepreneurship", count: 2, mean: 95, median: 95, mode: "95" },
 { course: "understandingincubationandenterpreneurship", count: 2, mean: 93.5, median: 93.5, mode: "No unique mode" },
 { course: "educationforsustainabledevelopement", count: 2, mean: 92, median: 92, mode: "No unique mode" },
 { course: "introductiontointernetofthings(iot)", count: 2, mean: 89.14, median: 89.14, mode: "No unique mode" },
 { course: "socialinnovationinindustry4.0", count: 2, mean: 87, median: 87, mode: "No unique mode" },
 { course: "psychologyofpersonalityandindividualdifferences:theoryandapplications", count: 2, mean: 85.5, median: 85.5, mode: "No unique mode" },
 { course: "gettingstartedwithcompetitiveprogramming", count: 2, mean: 84, median: 84, mode: "No unique mode" },
 { course: "joyofcomputing:python", count: 2, mean: 81.5, median: 81.5, mode: "No unique mode" },
 { course: "climatechangescience", count: 2, mean: 80.5, median: 80.5, mode: "No unique mode" },
 { course: "appliedergonomics", count: 2, mean: 76.5, median: 76.5, mode: "No unique mode" },
 { course: "introductiontoeconometrics", count: 2, mean: 75, median: 75, mode: "75" },
 { course: "mooccoursethermalphysics", count: 2, mean: 75, median: 75, mode: "No unique mode" },
 { course: "deeplearning-iitropar", count: 2, mean: 70.135, median: 70.135, mode: "No unique mode" },
 { course: "anintroductiontomicroeconomics", count: 2, mean: 70, median: 70, mode: "No unique mode" },
 { course: "gpuarchitecturesandprogramming", count: 2, mean: 66.5, median: 66.5, mode: "No unique mode" },
 { course: "blockchainanditsapplication", count: 2, mean: 64, median: 64, mode: "No unique mode" },
 { course: "programminginmodernc++", count: 2, mean: 52.5, median: 52.5, mode: "No unique mode" },
 { course: "productionandoperationmangement", count: 2, mean: 52, median: 52, mode: "52" },
 { course: "plasmaphysicsanditsapplications", count: 2, mean: 38, median: 38, mode: "38" },
 { course: "educationalforsustainabledevelopment", count: 1, mean: 100, median: 100, mode: "No unique mode" },
 { course: "educationforsustaiabledevelopment", count: 1, mean: 100, median: 100, mode: "No unique mode" },
 { course: "educationforsustainabledevelopmen", count: 1, mean: 100, median: 100, mode: "No unique mode" },
 { course: "educationtosustainabledevelopment", count: 1, mean: 100, median: 100, mode: "No unique mode" },
 { course: "energyresourcesandsustainability", count: 1, mean: 100, median: 100, mode: "No unique mode" },
 { course: "forestsandtheirmanagament", count: 1, mean: 100, median: 100, mode: "No unique mode" },
 { course: "forestsandtheirmanagement(noc20_bt01)", count: 1, mean: 100, median: 100, mode: "No unique mode" },
 { course: "softwaretesting", count: 1, mean: 100, median: 100, mode: "No unique mode" },
 { course: "wildlifeecology", count: 1, mean: 100, median: 100, mode: "No unique mode" },
 { course: "conservationaleconomics", count: 1, mean: 99, median: 99, mode: "No unique mode" },
 { course: "educationforsustainabledevelopment(noc25_hs12)", count: 1, mean: 99, median: 99, mode: "No unique mode" },
 { course: "educationforsustainanbledevelopment", count: 1, mean: 99, median: 99, mode: "No unique mode" },
 { course: "educationinsustainabledevelopment", count: 1, mean: 99, median: 99, mode: "No unique mode" },
 { course: "educationonsustainabledevelopment", count: 1, mean: 99, median: 99, mode: "No unique mode" },
 { course: "eductaionforsustainabledevelopment", count: 1, mean: 99, median: 99, mode: "No unique mode" },
 { course: "forestandtheirmanagement-online", count: 1, mean: 99, median: 99, mode: "No unique mode" },
 { course: "educationforsustainabilitydevelopment", count: 1, mean: 98, median: 98, mode: "No unique mode" },
 { course: "educationofsustainabilitydevelopment", count: 1, mean: 98, median: 98, mode: "No unique mode" },
 { course: "forestandmanagement", count: 1, mean: 98, median: 98, mode: "No unique mode" },
 { course: "noc25-hs12:educationforsustainabledevelopment", count: 1, mean: 98, median: 98, mode: "No unique mode" },
 { course: "Chutiya_BALAK", count: 1, mean: 97, median: 97, mode: "No unique mode" },
 { course: "forestandtheirmanagment", count: 1, mean: 97, median: 97, mode: "No unique mode" },
 { course: "sustainabledevelopment", count: 1, mean: 97, median: 97, mode: "No unique mode" },
 { course: "understandingincubationandentreprenuership", count: 1, mean: 97, median: 97, mode: "No unique mode" },
 { course: "forestandtheirmanagement(nptel)", count: 1, mean: 96, median: 96, mode: "No unique mode" },
 { course: "fuzzysets,logicandsystem&applications", count: 1, mean: 96, median: 96, mode: "No unique mode" },
 { course: "introductiontointernetofthing", count: 1, mean: 96, median: 96, mode: "No unique mode" },
 { course: "educationforsustainable development", count: 1, mean: 95, median: 95, mode: "No unique mode" },
 { course: "educationtosustainabledevlopment", count: 1, mean: 95, median: 95, mode: "No unique mode" },
 { course: "forestsandtheirmanagements", count: 1, mean: 95, median: 95, mode: "No unique mode" },
 { course: "intoductiontointernetofthings", count: 1, mean: 94, median: 94, mode: "No unique mode" },
 { course: "conservationeconomy", count: 1, mean: 93, median: 93, mode: "No unique mode" },
 { course: "contemporaryliterature", count: 1, mean: 93, median: 93, mode: "No unique mode" },
 { course: "dataanalyticsusingpython", count: 1, mean: 93, median: 93, mode: "No unique mode" },
 { course: "fuzzysets,logicandsystem&application", count: 1, mean: 93, median: 93, mode: "No unique mode" },
 { course: "fuzzysets,logicandsystemandapplications", count: 1, mean: 93, median: 93, mode: "No unique mode" },
 { course: "introductionininternetofthings", count: 1, mean: 93, median: 93, mode: "No unique mode" },
 { course: "introductionofinternetthings", count: 1, mean: 93, median: 93, mode: "No unique mode" },
 { course: "operationmanagement", count: 1, mean: 93, median: 93, mode: "No unique mode" },
 { course: "powerplantsystemengineering", count: 1, mean: 93, median: 93, mode: "No unique mode" },
 { course: "conversationeconomics", count: 1, mean: 92, median: 92, mode: "No unique mode" },
 { course: "introducingtointernetofthings", count: 1, mean: 92, median: 92, mode: "No unique mode" },
 { course: "educationforsustainabledevelopmemt", count: 1, mean: 91, median: 91, mode: "No unique mode" },
 { course: "conversationgeography", count: 1, mean: 90, median: 90, mode: "No unique mode" },
 { course: "fuzzysetsandlogic", count: 1, mean: 90, median: 90, mode: "No unique mode" },
 { course: "fuzzysetslogicandsystemsandapplications", count: 1, mean: 90, median: 90, mode: "No unique mode" },
 { course: "understandingincubationandentrepreneuship", count: 1, mean: 88, median: 88, mode: "No unique mode" },
 { course: "thejoyofcomputingusingpython(noc25-cs69)", count: 1, mean: 87, median: 87, mode: "No unique mode" },
 { course: "computerintegratedmanufacturing", count: 1, mean: 86, median: 86, mode: "No unique mode" },
 { course: "joyofcomputingwithpython", count: 1, mean: 86, median: 86, mode: "No unique mode" },
 { course: "mooccourse(mooc)", count: 1, mean: 86, median: 86, mode: "No unique mode" },
 { course: "thejoycomputingusingpython", count: 1, mean: 86, median: 86, mode: "No unique mode" },
 { course: "forests&theirmanagement", count: 1, mean: 85, median: 85, mode: "No unique mode" },
 { course: "forestandtheremanagement", count: 1, mean: 83, median: 83, mode: "No unique mode" },
 { course: "productdesign&manfacturing", count: 1, mean: 83, median: 83, mode: "No unique mode" },
 { course: "thejoyofcomputerusingpython", count: 1, mean: 83, median: 83, mode: "No unique mode" },
 { course: "introductiontomicroeconomics", count: 1, mean: 82, median: 82, mode: "No unique mode" },
 { course: "classicsinneuroscience", count: 1, mean: 81, median: 81, mode: "No unique mode" },
 { course: "cognitivepsycology", count: 1, mean: 81, median: 81, mode: "No unique mode" },
 { course: "forrestandtheirmanagement", count: 1, mean: 81, median: 81, mode: "No unique mode" },
 { course: "geographicinformationsystems", count: 1, mean: 80, median: 80, mode: "No unique mode" },
 { course: "thejoyofcomputingpython", count: 1, mean: 80, median: 80, mode: "No unique mode" },
 { course: "computerintergratedmanufacturing", count: 1, mean: 78, median: 78, mode: "No unique mode" },
 { course: "fuzzysets,logicsandsystems&applications", count: 1, mean: 78, median: 78, mode: "No unique mode" },
 { course: "introductiontotheinternetofthings", count: 1, mean: 78, median: 78, mode: "No unique mode" },
 { course: "thejoyofcomputingusingpython.", count: 1, mean: 78, median: 78, mode: "No unique mode" },
 { course: "iot", count: 1, mean: 77, median: 77, mode: "No unique mode" },
 { course: "advancedmachiningprocesses", count: 1, mean: 76, median: 76, mode: "No unique mode" },
 { course: "geographicinformationsystem", count: 1, mean: 76, median: 76, mode: "No unique mode" },
 { course: "sem1noc25:hs40introductiontocognitivepsychology-online", count: 1, mean: 76, median: 76, mode: "No unique mode" },
 { course: "cs44introductiontointernetofthings", count: 1, mean: 75, median: 75, mode: "No unique mode" },
 { course: "evolutionoftheearthandlife", count: 1, mean: 75, median: 75, mode: "No unique mode" },
 { course: "experimentalphysics-ii", count: 1, mean: 75, median: 75, mode: "No unique mode" },
 { course: "fuzzysets,logicandsystems&application", count: 1, mean: 75, median: 75, mode: "No unique mode" },
 { course: "introductiontomachinelearning", count: 1, mean: 75, median: 75, mode: "No unique mode" },
 { course: "fuzzysets,logicandsystem", count: 1, mean: 73, median: 73, mode: "No unique mode" },
 { course: "fuzzysets,logicsystemsandapplication", count: 1, mean: 73, median: 73, mode: "No unique mode" },
 { course: "organizationalbehaviour:individualdynamicsinorganization", count: 1, mean: 73, median: 73, mode: "No unique mode" },
 { course: "sensorsandattuators", count: 1, mean: 73, median: 73, mode: "No unique mode" },
 { course: "plasmaphysics", count: 1, mean: 72, median: 72, mode: "No unique mode" },
 { course: "entrepreneurshipessentials", count: 1, mean: 70, median: 70, mode: "No unique mode" },
 { course: "fuzzysets,logicsandsystems&application", count: 1, mean: 70, median: 70, mode: "No unique mode" },
 { course: "introductiontollm", count: 1, mean: 70, median: 70, mode: "No unique mode" },
 { course: "introductiontointernetofthingsintroductiontointernetofthings", count: 1, mean: 69, median: 69, mode: "No unique mode" },
 { course: "introductiontoenvironmentalengineeringandscience-fundamentalandsustainabilityconcepts", count: 1, mean: 68, median: 68, mode: "No unique mode" },
 { course: "joyofcomputingpython", count: 1, mean: 68, median: 68, mode: "No unique mode" },
 { course: "thejoyofcomputinhusingpython", count: 1, mean: 68, median: 68, mode: "No unique mode" },
 { course: "cloudcomuting", count: 1, mean: 67, median: 67, mode: "No unique mode" },
 { course: "digitalicdesign", count: 1, mean: 67, median: 67, mode: "No unique mode" },
 { course: "environmentalgeoscience", count: 1, mean: 67, median: 67, mode: "No unique mode" },
 { course: "cloudcmputing", count: 1, mean: 65, median: 65, mode: "No unique mode" },
 { course: "businessdevelopmentfromstarttoscale", count: 1, mean: 64, median: 64, mode: "No unique mode" },
 { course: "intellectualproperty", count: 1, mean: 64, median: 64, mode: "No unique mode" },
 { course: "joyofpython", count: 1, mean: 63, median: 63, mode: "No unique mode" },
 { course: "cs11cloudcomputing", count: 1, mean: 62, median: 62, mode: "No unique mode" },
 { course: "maternalinfantandyoungchildnutrition", count: 1, mean: 61, median: 61, mode: "No unique mode" },
 { course: "modernconstructionmaterial", count: 1, mean: 61, median: 61, mode: "No unique mode" },
 { course: "naturallanguageprocessing(noc25-cs51)", count: 1, mean: 61, median: 61, mode: "No unique mode" },
 { course: "appliedlinearalgebra", count: 1, mean: 60, median: 60, mode: "No unique mode" },
 { course: "deeplearningfornaturallanguageprocessing", count: 1, mean: 60, median: 60, mode: "No unique mode" },
 { course: "introductiontojapanese", count: 1, mean: 58, median: 58, mode: "No unique mode" },
 { course: "privacyandsecurityinsocialmedia", count: 1, mean: 57, median: 57, mode: "No unique mode" },
 { course: "computervisionandimageprocessing", count: 1, mean: 56, median: 56, mode: "No unique mode" },
 { course: "internationalbusiness", count: 1, mean: 55, median: 55, mode: "No unique mode" },
 { course: "reinforcementlearning", count: 1, mean: 53, median: 53, mode: "No unique mode" },
 { course: "introductiontojapaneselanguageandculture", count: 1, mean: 51, median: 51, mode: "No unique mode" },
 { course: "noisemanagmentandcontrol", count: 1, mean: 51, median: 51, mode: "No unique mode" },
 { course: "plasmaphysicsandapplication", count: 1, mean: 50, median: 50, mode: "No unique mode" },
 { course: "socialnetwork", count: 1, mean: 50, median: 50, mode: "No unique mode" },
 { course: "noisecontrolinmechanicalsystems", count: 1, mean: 49, median: 49, mode: "No unique mode" },
 { course: "trafficengineering", count: 1, mean: 45, median: 45, mode: "No unique mode" },
 { course: "physicsofrenewablesystems", count: 1, mean: 39, median: 39, mode: "No unique mode" },
 { course: "plasmaphysicsanditsapplication", count: 1, mean: 39, median: 39, mode: "No unique mode" },
];

document.addEventListener('DOMContentLoaded', () => {
    const tableBody = document.querySelector("#data-table tbody");
    const headers = document.querySelectorAll("#data-table thead th");
    const searchInput = document.getElementById('searchInput');
    const btn2024 = document.getElementById('btn2024');
    const btn2025 = document.getElementById('btn2025');

    let activeData = data1; 

    const renderTable = (dataToRender) => {
        tableBody.innerHTML = '';
        dataToRender.forEach(row => {
            const tr = document.createElement('tr');
            tr.innerHTML = `
                <td>${row.course}</td>
                <td>${row.count}</td>
                <td>${row.mean.toFixed(2)}</td>
                <td>${row.median}</td>
                <td>${row.mode}</td>
            `;
            tableBody.appendChild(tr);
        });
    };

    const updateView = () => {
        const searchTerm = searchInput.value.toLowerCase().trim();
        const filteredData = activeData.filter(row => 
            row.course.toLowerCase().includes(searchTerm)
        );
        renderTable(filteredData);
    };

    const sortData = (column, type, direction) => {
        const modifier = direction === 'asc' ? 1 : -1;
        activeData.sort((a, b) => {
            const valA = a[column];
            const valB = b[column];
            if (type === 'number') {
                return (valA - valB) * modifier;
            } else {
                return valA.localeCompare(valB) * modifier;
            }
        });
        updateView();
    };

    searchInput.addEventListener('input', updateView);

    headers.forEach(header => {
        header.addEventListener('click', () => {
            const column = header.dataset.column;
            const type = header.dataset.type;
            const direction = header.classList.contains('sort-asc') ? 'desc' : 'asc';
            
            headers.forEach(h => h.classList.remove('sort-asc', 'sort-desc'));
            header.classList.add(direction === 'asc' ? 'sort-asc' : 'sort-desc');
            
            sortData(column, type, direction);
        });
    });

    btn2024.addEventListener('click', () => {
        activeData = data1;
        searchInput.value = '';
        btn2024.classList.add('active');
        btn2025.classList.remove('active');
        headers.forEach(h => h.classList.remove('sort-asc', 'sort-desc'));
        updateView();
    });

    btn2025.addEventListener('click', () => {
        activeData = data2;
        searchInput.value = '';
        btn2025.classList.add('active');
        btn2024.classList.remove('active');
        headers.forEach(h => h.classList.remove('sort-asc', 'sort-desc'));
        updateView();
    });

    // --- NEW CODE: Check for mobile screen size and adjust note font ---
    const checkScreenSize = () => {
        const disclaimer = document.querySelector('.disclaimer');
        // window.innerWidth gives the browser's actual width
        if (window.innerWidth < 768) {
            disclaimer.classList.add('mobile-view');
        } else {
            disclaimer.classList.remove('mobile-view');
        }
    };
    
    checkScreenSize(); 
    updateView();
});
